# =======================================================================
# 基础物理极限（Phys-safe） ------------------------------------------------
# =======================================================================
phys_safe:
  # 纵向最大减速度   a_lon,max   (m/s²)
  a_lon_dec_av:   4.0            # Ego / AV
  a_lon_dec_npc:  4.0            # NPC
  # 横向最大减速度   a_lat,max   (m/s²)
  a_lat_dec_av:   1.5
  a_lat_dec_npc:  1.5
  # 数值安全微量     EPS
  eps:            1.0e-4
  INF_DIST:       10000     # 10 km 已远超 CARLA 地图
  # yaw 判定阈值 (deg)
  th_same_dir:    30             # |Δyaw| ≤ 30°   → 同向
  th_oppo_dir:    150            # |Δyaw| ≥ 150°  → 迎面
  # 横向安全距离给个最小缓冲 (m)
  min_lat_safe:   0.30

# =======================================================================
# ADV 奖励参数 ------------------------------------------------------------
# =======================================================================
adv_reward:
  w_ttc:          0.7            # TTC 权重
  w_headway:      0.3            # Head-way 权重
  ttc_horizon:    3.0            # s，≤此时间视为高风险
  desired_headway: 1.8           # s，法规推荐跟车时距

# =======================================================================
# 场景总奖励权重 -----------------------------------------------------------
# =======================================================================
scenario_reward:
  w_phys:         1.0            # 物理解奖励权重
  w_adv:          3.0            # ADV 奖励权重

